---
- hosts: 172.31.1.58
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserevr
    apt:
      name: apache2
  - name: wnt to copy statuc fuke to ansibke node
    copy:
     src: mystatuc.txt
     dest: /home/maha/mystatic.txt
