---
- hosts: 172.31.1.58
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserevr
    apt:
      name: apache2
  - name: wnt to copy statuc fuke to ansibke node
    copy:
     src: mystatic.txt
     dest: /home/maha/mystatic.txt
    notify: restartwebserevr
  - name: dyno faile copy
    template:
     src: mydynofile.j2
     dest: /var/www/html/index.html
    notify: restartwebserevr
  - name: i wnat to download remote fiels
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69-deployer.tar.gz
      dest: /home/maha/ 
      force_basic_auth: yes
 
  handlers:
  - name: restartwebserevr
    service:
      name: apache2
      state: restarted
