---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want o install apache2 on ubuntu
    apt:
     name: "{{webpackonubuntu}}"
     state: present
    when: ansible_os_family=="Debian" 
  - name: i want start apache2
    service:
     name: "{{webpackonubuntu}}"
     state: started
    when: ansible_os_family=="Debian"
  - name: i want to install http on redhat
    yum:
     name: "{{webpackonredhat}}"
     state: present
    when: ansible_os_family=="RedHat"
  - name: start httpd
    service:
     name: "{{webpackonredhat}}"
     state: present 
    when: ansible_os_family=="RedHat"

